file_format: "1"
id: cornettux
name: CORNETTUX
type: shield
url: https://github.com/lbourne43/zmk-config-cornettux/
requires: [pro_micro]
features:
  - keys
siblings:
  - cornettux_left
  - cornettux_right
