file_format: "1"
id: cornettux
name: cornettux
type: shield
url: https://github.com/lbourne43/zmk-config-cornettux/
requires: [nice!nanov2]
features:
  - keys
siblings:
  - cornettux_left
  - cornettux_right
